name: Node.js CI

on: [push, pull_request]

defaults:
  run:
    working-directory: backend

jobs:
  build:
    name: Lint Code Base
    runs-on: ${{matrix.os}}
    strategy:
      max-parallel: 24
      matrix:
        os: [ubuntu-latest]
        node-version: [18.x]

    steps:

      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_JAVASCRIPT_ES: true
      - run: npm ci
      - run: npm test